[package]
name = "opaque-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opaque-ke = "2"
rand = "0.8.5"
aes-gcm = "0.10.3"
threadpool = "1.8.1"